### ISSUE TITLE
[Anki 2.1.22] ImportError: cannot import name 'furigana' from 'anki.template'

### ISSUE THREAD

**Issue by MrPiethon** [HelenFoster/JSentenceHighlighter#7]
Debug info:
Anki 2.1.22 (0ecc189a) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 10
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-04-20 22:30:36

Caught exception:
Traceback (most recent call last):
  File "C:\Users\\AppData\Roaming\Anki2\addons21\jsentencehighlighter\__init__.py", line 24, in highlightAllSentences
    highlightSentences(None)
  File "C:\Users\\AppData\Roaming\Anki2\addons21\jsentencehighlighter\__init__.py", line 18, in highlightSentences
    from . import run
  File "C:\Users\\AppData\Roaming\Anki2\addons21\jsentencehighlighter\run.py", line 10, in <module>
    from anki.template import furigana
ImportError: cannot import name 'furigana' from 'anki.template' (C:\Program Files\Anki\anki\template.pyc)

**Comment by HelenFoster** [comment]
Same problem as https://github.com/HelenFoster/KanjiVocab/issues/15
